In [15]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [17]:
%reload_ext kedro.ipython

[10/29/25 12:33:05] INFO     Registered line magic '%reload_kedro'                                   ]8;id=618402;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=811393;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py#63\63]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=486770;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=803496;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py#65\65]8;;\

                    INFO     Resolved project path as:                                              ]8;id=958466;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=54691;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py#180\180]8;;\
                             c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\spaceflights.
                             To set a different path, run '%reload_kedro <project_root>'

[10/29/25 12:33:08] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=2468;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=83472;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro_telemetry\plugin.py#243\243]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

                    DEBUG    Failed to send data to Heap. Exception of type 'SSLError' was raised.    ]8;id=6791;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=697603;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro_telemetry\plugin.py#358\358]8;;\

                    INFO     Kedro project spaceflights                                             ]8;id=834600;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=959447;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py#146\146]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=119594;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=639437;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\
                             'pipelines'

[10/29/25 12:33:10] INFO     Registered line magic 'run_viz'                                        ]8;id=965229;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=377989;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py#153\153]8;;\

In [2]:
df = catalog.load("model_input_table")
df.head()

[10/29/25 09:54:22] INFO     Loading data from model_input_table (ParquetDataset)...            ]8;id=257559;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=841764;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\io\data_catalog.py#403\403]8;;\

,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,...,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month,id,company_rating,company_location,total_fleet_count,iata_approved
0,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,False,...,9.0,9.0,9.0,26,0.77,32413,1.0,Faroe Islands,1.0,False
1,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,False,...,10.0,10.0,9.0,61,0.62,14122,1.0,Malta,1.0,True
2,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,False,...,10.0,10.0,10.0,467,4.66,47761,1.0,Niue,2.0,False
3,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,False,...,10.0,9.0,9.0,318,3.22,26648,1.0,Niue,2.0,True
4,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,False,...,10.0,9.0,10.0,22,0.29,26648,1.0,Niue,2.0,True

In [3]:
import sklearn

In [4]:
sklearn.__version__

'1.7.2'

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
features = [
    "engines",
    "passenger_capacity",
    "crew",
    "d_check_complete",
    "moon_clearance_complete",
    "iata_approved",
    "company_rating",
    "review_scores_rating",
]

In [12]:
X = df[features]
y = df["price"]

In [13]:
X.head()

,engines,passenger_capacity,crew,d_check_complete,moon_clearance_complete,iata_approved,company_rating,review_scores_rating
0,2.0,4,2.0,False,False,False,1.0,91.0
1,3.0,5,3.0,False,False,True,1.0,96.0
2,1.0,2,1.0,True,False,False,1.0,97.0
3,1.0,2,1.0,False,False,True,1.0,95.0
4,5.0,10,5.0,False,False,True,1.0,97.0

In [14]:
y.head()

0    1715.0
1    3405.0
2    1806.0
3    1676.0
4    4718.0
Name: price, dtype: float64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=parameters["test_size"], random_state=parameters["random_state"]
)

In [19]:
%reload_kedro

[10/29/25 12:34:25] INFO     Resolved project path as:                                              ]8;id=498556;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=847215;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py#180\180]8;;\
                             C:\Users\sebastian.calderon\Documents\GitHub\work\kedro\spaceflights.
                             To set a different path, run '%reload_kedro <project_root>'

[10/29/25 12:34:28] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=830778;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=828619;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro_telemetry\plugin.py#243\243]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

[10/29/25 12:34:29] DEBUG    Failed to send data to Heap. Exception of type 'SSLError' was raised.    ]8;id=987961;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=654499;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro_telemetry\plugin.py#358\358]8;;\

                    INFO     Kedro project spaceflights                                             ]8;id=333372;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=233576;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py#146\146]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=188611;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=448503;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\
                             'pipelines'

[10/29/25 12:34:30] INFO     Registered line magic 'run_viz'                                        ]8;id=677563;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=395872;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\ipython\__init__.py#153\153]8;;\

In [20]:
catalog.load("params:a")

[10/29/25 12:34:32] INFO     Loading data from params:a (MemoryDataset)...                      ]8;id=241999;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=77534;file://c:\Users\sebastian.calderon\Documents\GitHub\work\kedro\venv\Lib\site-packages\kedro\io\data_catalog.py#403\403]8;;\

1